import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize OpenAI Client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def generate_ad_copy(product, audience, benefits, tone, copy_type):
    """
    Generates ad copy variations using OpenAI based on specific parameters.
    
    Args:
        product (str): Product/Service description.
        audience (str): Target Audience.
        benefits (str): Key Benefits.
        tone (str): Desired tone (e.g., Professional, Friendly).
        copy_type (str): Type of copy (Headlines, Primary Text, Descriptions, CTAs).
        
    Returns:
        list: A list of string variations generated by the AI.
    """
    
    # 1. Define the System Persona and Rules
    system_prompt = f"""
    You are an AI Advertising Copywriting Assistant integrated into AdPortal.
    Your job is to generate high-quality, conversion-focused ad copy.
    
    STRICT OUTPUT FORMAT:
    You must return a raw JSON object with a single key "variations" containing a list of strings.
    Example: {{ "variations": ["Option 1", "Option 2", "Option 3"] }}
    
    RULES BY COPY TYPE:
    - If Copy Type is 'Headlines': Generate 4 short, scroll-stopping headlines (8-12 words max).
    - If Copy Type is 'Primary Text': Generate 4 distinct variations. Write exactly ONE paragraph.It must be between 2 to 3 sentences long.
    - If Copy Type is 'Descriptions': Generate 4 concise descriptions (1-2 lines max).
    - If Copy Type is 'CTAs': Generate 4 strong Call to Action phrases.
    
    GENERAL GUIDELINES:
    - Tone: {tone}
    - Do NOT mention AI, Models, or "As an AI".
    - No markdown formatting in the text (except the outer JSON).
    """

    # 2. Construct the User Prompt
    user_prompt = f"""
    Generate {copy_type} for the following context:
    
    Product/Service: {product}
    Target Audience: {audience}
    Key Benefits: {benefits}
    """

    try:
        # 3. Call OpenAI API
        response = client.chat.completions.create(
            model="gpt-4o", # Or "gpt-3.5-turbo" for lower cost
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.7, # Balance between creativity and professional adherence
            response_format={ "type": "json_object" } # Ensures valid JSON output
        )

        # 4. Parse JSON Response
        data = json.loads(response.choices[0].message.content)
        return data.get("variations", [])

    except Exception as e:
        return [f"Error generating copy: {str(e)}"]